### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ShereeMorphett**
Im attempting to add the develop branch onto the main

### CODE REVIEW

**Comment by jboucher154** [comment]
sounds good!

**Review by jboucher154 — CHANGES_REQUESTED** [review]
We just need to remove the DS.Store file from libft

**Review by jboucher154 — APPROVED** [review]

**Review by jboucher154 — APPROVED** [review]

**Review by ShereeMorphett — COMMENTED** [review]
Im not sure if I just need to answer to make this complete?

**Review by jboucher154 — APPROVED** [review]
Looks good

**Pull request merged**
